#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const hookPath = path.join(process.cwd(), '.git', 'hooks', 'pre-commit');
const hookScript = `#!/bin/sh
# Auto-generated by scripts/install-hooks.js

npm run test
`;

function installHooks() {
  if (!fs.existsSync(path.join(process.cwd(), '.git', 'hooks'))) {
    console.log('No .git/hooks directory found. Skipping hook installation.');
    return;
  }

  try {
    fs.writeFileSync(hookPath, hookScript, { mode: 0o755 });
    console.log('Successfully installed pre-commit hook.');
  } catch (err) {
    console.error('Failed to install pre-commit hook:', err.message);
  }
}

installHooks();
